LIBKIND    := shared
LIBNAME    := liboshot_imgui
SRC        := $(wildcard *.cpp)
VISIBILITY := default

CXXFLAGS += -I../../../include/libs/imgui -DIMGUI_DISABLE_OBSOLETE_FUNCTIONS

include ../../../mk/common.mk
