LIBKIND    := shared
LIBNAME    := liboshot_cimgui
SRC        += cimgui.cpp
VISIBILITY := default

CXXFLAGS  += -I../../../include/libs/cimgui -I../../../include/libs/
EXTRA_LIBS = -L../../../$(BUILDDIR) -loshot_imgui

include ../../../mk/common.mk
