#include "cache.hpp"

#include <filesystem>
#include <fstream>
#include <string>

#include "fmt/format.h"
#include "toml++/toml.hpp"
#include "util.hpp"

// https://github.com/hyprwm/Hyprland/blob/2d2a5bebff72c73cd27db3b9e954b8fa2a7623e8/hyprpm/src/core/DataState.cpp#L24
static bool write_cache(const std::string& str, const std::string& to)
{
    // create temp file in a safe temp root
    const fs::path temp_state = (fs::temp_directory_path() / ".temp-cache");
    std::ofstream  of(temp_state, std::ios::trunc);
    if (!of.good())
        return false;

    of << str;
    of.close();

    return fs::copy_file(temp_state, to, fs::copy_options::overwrite_existing);
}

Cache::Cache(const std::string& cache_dir) : m_cache_dir_path(cache_dir)
{
    if (!fs::exists(cache_dir))
    {
        warn("Oshot cache folder was not found. Creating folders at {}!", cache_dir);
        fs::create_directories(cache_dir);
    }

    MUST_OK(LoadCacheFile(), error("{}", _r.error_v()));
}

Cache::~Cache()
{
    CdGuard guard(m_cache_dir_path);

    std::stringstream ss;
    ss << "# AUTO-GENERATED FILE. DO NOT EDIT THIS FILE.\n"
          "# YOU GONNA MESS SHIT UP. unless you know what you doing ofc\n";
    ss << m_tbl;

    if (!write_cache(ss.str(), mk_file_path))
        error("Failed to write cache entry at path '{}'", mk_file_path);
}

Result<> Cache::LoadCacheFile()
{
    // Since the filename (default.theme-file) will be likely
    // related to relative path of the config directory, let's
    // snapshot and switch to that directory.
    CdGuard guard(m_cache_dir_path);

    try
    {
        if (fs::exists(mk_file_path))
            m_tbl = toml::parse_file(mk_file_path);
    }
    catch (const toml::parse_error& err)
    {
        return Err(
            fmt::format("Parsing cache file '{}' failed:\n"
                        "{}\n"
                        "\t(error occurred at line {} column {})",
                        mk_file_path,
                        err.description(),
                        err.source().begin.line,
                        err.source().begin.column));
    }

    return Ok();
}
