#include "cache.hpp"

#include <filesystem>
#include <fstream>
#include <string>

#include "fmt/format.h"
#include "toml++/toml.hpp"
#include "util.hpp"

std::unordered_map<CacheFilesEnum, cache_entry_t> g_cache_files = {
    { CacheFilesEnum::Colors, { "colors.toml", "cache.default-color-picker-color" } }
};

static fs::path old_pwd;
static void     cd(const fs::path& path)
{
    if (!path.empty())
    {
        old_pwd = fs::current_path();
        fs::current_path(path);
    }
}

static void cd_back()
{
    if (!old_pwd.empty())
        fs::current_path(old_pwd);
}

// https://github.com/hyprwm/Hyprland/blob/2d2a5bebff72c73cd27db3b9e954b8fa2a7623e8/hyprpm/src/core/DataState.cpp#L24
static bool write_cache(const std::string& str, const std::string& to)
{
    // create temp file in a safe temp root
    const fs::path& temp_state = (fs::temp_directory_path() / ".temp-state");
    std::ofstream   of(temp_state, std::ios::trunc);
    if (!of.good())
        return false;

    of << str;
    of.close();

    return fs::copy_file(temp_state, to, fs::copy_options::overwrite_existing);
}

Cache::Cache(const std::string& cache_dir) : m_cache_dir_path(cache_dir)
{
    if (!fs::exists(cache_dir))
    {
        warn("oshot cache folder was not found, Creating folders at {}!", cache_dir);
        fs::create_directories(cache_dir);
    }

    for (int i = 0; i < int(idx(CacheFilesEnum::COUNT)); ++i)
        LoadCacheFile(g_cache_files[enum_<CacheFilesEnum>(i)]);
}

Cache::~Cache()
{
    for (const auto& [_, cache] : g_cache_files)
        GenerateCacheFile(cache);
}

Result<> Cache::LoadCacheFile(cache_entry_t& entry)
{
    // Since the filename (default.theme-file) will be likely
    // related to relative path of the config directory, let's
    // snapshot and switch to that directory.
    cd(m_cache_dir_path);

    if (fs::exists(entry.file_path))
    {
        try
        {
            entry.tbl = toml::parse_file(entry.file_path);
        }
        catch (const toml::parse_error& err)
        {
            // Snap back
            cd_back();
            return Err(
                fmt::format("Parsing cache file '{}' failed:\n"
                            "{}\n"
                            "\t(error occurred at line {} column {})",
                            entry.file_path,
                            err.description(),
                            err.source().begin.line,
                            err.source().begin.column));
        }
    }

    cd_back();
    return Ok();
}

void Cache::GenerateCacheFile(const cache_entry_t& entry)
{
    cd(m_cache_dir_path);

    std::stringstream ss;
    ss << "# AUTO-GENERATED FILE. DO NOT EDIT THIS FILE.\n";
    ss << "# YOU GONNA MESS SHIT UP. unless you know what you doing ofc\n";
    ss << entry.tbl;

    if (!write_cache(ss.str(), entry.file_path))
        error("Failed to write cache entry at path '{}'", entry.file_path);
    cd_back();
}
