/*
 * Copyright 2026 Toni500
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
 * following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following
 * disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 * following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote
 * products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#include "cache.hpp"

#include <filesystem>
#include <string>

#include "util.hpp"

Cache::Cache(const std::string& cache_dir) : m_cache_dir_path(cache_dir)
{
    if (!fs::exists(cache_dir))
    {
        spdlog::warn("Oshot cache folder was not found. Creating folders at {}!", cache_dir);
        fs::create_directories(cache_dir);
        CreateFile();
    }

    MUST_OK(LoadCacheFile(), spdlog::error("{}", _r.error_v()));
}

Cache::~Cache()
{
    CreateFile();
}

void Cache::CreateFile()
{
    CdGuard guard(m_cache_dir_path);

    std::stringstream ss;
    ss << "# AUTO-GENERATED FILE. DO NOT EDIT THIS FILE.\n"
          "# YOU GONNA MESS SHIT UP. unless you know what you doing ofc\n";
    ss << m_tbl;

    if (!SaveFile(ss.str(), mk_file_path))
        error("Failed to write cache entry at path '{}'", mk_file_path);
}

Result<> Cache::LoadCacheFile()
{
    // Since the filename (default.theme-file) will be likely
    // related to relative path of the config directory, let's
    // snapshot and switch to that directory.
    CdGuard guard(m_cache_dir_path);

    return LoadFile(mk_file_path);
}
